### ISSUE TITLE
cssnano ignores browserslist in package.json

### ISSUE THREAD

**Issue by Dattaya** [NMFR/optimize-css-assets-webpack-plugin#100]
Is it normal that cssnano ignores browserslist in package.json?
This works:
```js
    new OptimizeCssAssetsPlugin({
      cssProcessorPluginOptions: {
        preset: ['advanced', { autoprefixer: { browsers: ["chrome > 1"] }, zindex: false, reduceIdents: false, mergeIdents: false, discardUnused: false }],
      },
    }),
```
but if I remove `autoprefixer: { browsers: ["chrome > 1"] },` and leave only `"browserslist": [    "chrome > 1"],` in my `package.json`, autoprefixer does not work.

**Comment by NMFR** [comment]
It should if its a cssnano feature. Dont think we can help with that one this repo. Could you please open the issue on the cssnano repo?

Closing for now, please comment on this issue if there is an update and if we need to reopen this.
