### ISSUE TITLE
Bump js-yaml

### ISSUE THREAD

**Issue by sergio-bravo** [NMFR/optimize-css-assets-webpack-plugin#104]
`yarn audit` brings high severity warning:

high          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ optimize-css-assets-webpack-plugin                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ optimize-css-assets-webpack-plugin > cssnano > cosmiconfig > │
│               │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/813

**Comment by Schnueggel** [comment]
Fails for me also with a fresh installation

**Comment by NMFR** [comment]
`v5.0.2` (just released) should have fix this.
