### ISSUE TITLE
optimize-css-assets-webpack-plugin@3.2.0 vulnerabilities

### ISSUE THREAD

**Issue by klouzoun** [NMFR/optimize-css-assets-webpack-plugin#105]
When I run npm audit on optimize-css-assets-webpack-plugin@3.2.0, two vulnerabilities are found in js-yaml:

One moderate : Denial of Service
More info     │ https://npmjs.com/advisories/788

One High: Code Injection
More info     │ https://npmjs.com/advisories/813

Have you planned to update version in order to fix it?

Kevin.

**Comment by josephting** [comment]
Doing a clean `npm install` may be able to fix it.
If it still doesn't, perhaps try doing a clean install after deleting `package-lock.json`.

**Comment by klouzoun** [comment]
@josephting vulnerabilities (Code Injection and Denial of Service) are from a sub-dependecy of `js-yaml` package:

optimize-css-assets-webpack-plugin > cssnano > postcss-svgo > svgo > js-yaml

**Comment by josephting** [comment]
@klouzoun I think there's no other way other than upgrading to `optimize-css-assets-wepback-plugin@5.0.0` or above.

**Comment by NMFR** [comment]
`3.2.1` should solve this problem.
