### ISSUE TITLE
npm run build problem

### ISSUE THREAD

**Issue by jagdishkhudiya** [NMFR/optimize-css-assets-webpack-plugin#106]
compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (C:\wamp\www\vender_v1\node_modules\last-call-webpack-plugin\src\index.js:170:20)
    at Compiler.apply (C:\wamp\www\vender_v1\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\wamp\www\vender_v1\node_modules\webpack\lib\webpack.js:32:19)
    at C:\wamp\www\vender_v1\build\build.js:19:3
    at next (C:\wamp\www\vender_v1\node_modules\rimraf\rimraf.js:75:7)
    at CB (C:\wamp\www\vender_v1\node_modules\rimraf\rimraf.js:111:9)
    at C:\wamp\www\vender_v1\node_modules\rimraf\rimraf.js:137:14
    at FSReqCallback.oncomplete (fs.js:165:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vender_v1@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vender_v1@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jagdishkhudiya** [comment]
"devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^3.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^4.0.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^2.0.1",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },

**Comment by NMFR** [comment]
As stated in the README:

For webpack v3 or below please use optimize-css-assets-webpack-plugin@3.2.0. The optimize-css-assets-webpack-plugin@4.0.0 version and above supports webpack v4.

So either upgrade to webpack 4 or above or use optimize-css-assets-webpack-plugin@3.2.0 or below for webpack 3 and below.
