### ISSUE TITLE
Incorrect compress on calc()

### ISSUE THREAD

**Issue by leecjson** [NMFR/optimize-css-assets-webpack-plugin#110]
calc(1279px - 100px - (100vw - 100%)) 
will compress to 
calc(1179px - 100vw - 100%);

btw 100vw not equivalent to 100%

**Comment by coreyworrell** [comment]
Having a similar issue here as well.

```css
--fluid-bp: calc(
    (var(--fluid-screen) - ((var(--fluid-min-width) / 16) * 1rem)) /
    ((var(--fluid-max-width) / 16) - (var(--fluid-min-width) / 16))
);
```

compresses to:

```css
--fluid-bp:calc((var(--fluid-screen) - var(--fluid-min-width)/16*1rem)/(var(--fluid-max-width) - var(--fluid-min-width)))
```

which is missing some of the divisions.

Looks like this library may be dead anyways, time to look for a new solution.

**Comment by coreyworrell** [comment]
Real issue lies here: https://github.com/postcss/postcss-calc/issues/107

**Comment by NMFR** [comment]
Closing, this is a cssProcessor issue (cssnano), i am afraid no change in this repo will help.
