### ISSUE TITLE
background-image

### ISSUE THREAD

**Issue by zhangchao828** [NMFR/optimize-css-assets-webpack-plugin#112]
input：
background: url('https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=508387608,2848974022&fm=26&gp=0.jpg?imageView2/1/w/750/h/1334');

output：
background: url('https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=508387608,2848974022&fm=26&gp=0.jpg?imageView2%2F1%2Fw%2F750%2Fh%2F1334');

/->%2F

**Comment by NMFR** [comment]
This plugin does not really touch any css, it delegates it to the css processor that by default is cssnano. So this is either a cssnano issue or your configured processor. I am afraid i cannot help you here. But if you manage to find the source of the problem please comment in this issue to help anyone that is struggling with the same issue.
