### ISSUE TITLE
CSS variables improperly minified in `font` shorthand 

### ISSUE THREAD

**Issue by rileyjshaw** [NMFR/optimize-css-assets-webpack-plugin#113]
The CSS: `font: 900 var(--font-size) var(--font-family)`

Becomes: `font:900 var(--font-size),var(--font-family)` when minified.

---

The comma between `var(--font-size)` and `var(--font-family)` in the output causes an error.

**Comment by NMFR** [comment]
This plugin does not really touch any css, it delegates it to the css processor that by default is cssnano. So this is either a cssnano issue or your configured processor. I am afraid i cannot help you here. But if you manage to find the source of the problem please comment in this issue to help anyone that is struggling with the same issue.
