### ISSUE TITLE
Problem with cssnano dependency: error when run webpack

### ISSUE THREAD

**Issue by jyeros** [NMFR/optimize-css-assets-webpack-plugin#115]
I have this package as dependency and when i run webpack i have the next error
```
Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined
    at promises.push.getSvgo.optimize.then.catch.error (C:\Projects\temp\src\main\node_modules\postcss-svgo\dist\index.js:95:19)
    at <anonymous>
```
I search a version of `package-lock.json` that work and change the reference `svgo` from `1.3.1` to `1.2.2` it works. 

I saw this packages have `"cssnano": "^4.1.10"` as dependency and it have `"postcss-svgo": "^4.0.2"` as dependency that have `"svgo": "^1.0.0"` as dependency and it is the version with problem, i don't know how fix it without modify the `package-lock.json` manually

Maybe it isn't an issue with your code, but i open the issue here because i am using this package as dependency not the others.

**Comment by liuhao189** [comment]
也遇到了这个问题

**Comment by qianzhangsheng** [comment]
me too

**Comment by yoyeung** [comment]
Please try to add “svgo”: “1.3.0” in your dependence session to freeze the svgo version

**Comment by djlxiaoshi** [comment]
please try to use version 5.0.1

**Comment by jyeros** [comment]
> Please try to add “svgo”: “1.3.0” in your dependence session to freeze the svgo version

I use this version and works, look like the version with problem is `1.3.1` there is a new release https://github.com/svg/svgo/releases/tag/v1.3.2 and it works for me too
