### ISSUE TITLE
Compatibility with webpack-subresource-integrity

### ISSUE THREAD

**Issue by hitchcott** [NMFR/optimize-css-assets-webpack-plugin#12]
Currently this package is incompatible with Subresource Integrity, apparently due to incorrect use of the `emit` event.

https://github.com/waysact/webpack-subresource-integrity/issues/47

 
> [optimize-css-assets-webpack-plugin] performs the optimization in the emit phase, and as such is incompatible with webpack-subresource-integrity. By that point the integrity hashes have already been computed, and so any changes to the asset contents will cause breakage.
> 
> I think the correct fix here is to ask the authors of optimize-css-assets-webpack-plugin to perform the optimization in the optimize phase instead, perhaps using the optimize-chunk-assets hook.
> 
> Let me know in case the other plugin has a good reason for hooking into the emit phase instead of the optimize phase and I'm happy to take another look at this.

**Comment by NMFR** [comment]
``` optimize-chunk-assets ``` seems to be close enough to the end of the compilation to work, but it needs some testing (specially with extract-text-webpack-plugin).

I will only have time to work on this about in two weeks.

**Comment by NMFR** [comment]
Solved with version `3.0.0`.
