### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by hdxqnljs** [NMFR/optimize-css-assets-webpack-plugin#124]
![image](https://user-images.githubusercontent.com/20278807/80349990-a9055580-88a2-11ea-9193-0d53c3e1b330.png)
![image](https://user-images.githubusercontent.com/20278807/80350030-b6224480-88a2-11ea-9f30-b67677f8621b.png)
help me, please

**Comment by markymc** [comment]
@hdxqnljs Could you please share your solution to this? I'm seeing a similar problem. Thanks!

**Comment by hdxqnljs** [comment]
> @hdxqnljs Could you please share your solution to this? I'm seeing a similar problem. Thanks!

![image](https://user-images.githubusercontent.com/20278807/132611160-3fcdd0d9-de9a-453e-bb68-2bae28ddd35a.png)
something like this....my mistake
