### ISSUE TITLE
Confused by usage info

### ISSUE THREAD

**Issue by wintercounter** [NMFR/optimize-css-assets-webpack-plugin#127]
In Webpack docs it says I need to add it to `optimization.minimizer` (https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production). Here it says I have to add to plugins. I guess have to use the Webpack way of I want to use only as a final step in production, and the mentioned method in the plugin's docs when I always want to run it. Can we clear up things here please?

**Comment by NMFR** [comment]
Webpack recommends to define the plugin in `optimization.minimizer` (https://webpack.js.org/configuration/optimization/) so the plugin only runs if mode is `production`. I guess to improve compile speed in development. 

I prefer to suggest to always have it enable so the development and production results are the same and decrease the amount of surprises. I believe the development and production builds should be as similar as possible. So it is really up to you if you want to only run in production builds or always.

I am closing this as i think we should suggest to always run it. If anyone disagrees please comment in this issue and i will reopen and lets have a discussion if the README should be changed.
