### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by herrvigg** [NMFR/optimize-css-assets-webpack-plugin#131]
No update since June 2019.
Many open PRs and issues opened since that time without any answer.
Should we consider this repo abandoned?

**Comment by NMFR** [comment]
Apologies for that, i have been very busy at work and haven't had time to address issues.
I also have fallen a bit behind on issues due to many of them being false positives caused by css-nano issues.

I will try to dedicate some time to this in the following weeks
