### ISSUE TITLE
[question] will the 5.x version work with webpack 5? do we have plan to make this plugin work with webpack5?

### ISSUE THREAD

**Issue by achenwei-chwy** [NMFR/optimize-css-assets-webpack-plugin#134]

**Comment by thijstriemstra** [comment]
webpack 5 has been released.

**Comment by NMFR** [comment]
Will work on supporting webpack 5 this weekend.

**Comment by fwh1990** [comment]
Would u please provide type definition file? Because `@types/optimize-css-assets-webpack-plugin` is not compatible with webpack@5

**Comment by NMFR** [comment]
I am thinking of deprecating [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) and pointing people to [css-minimizer-webpack-plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin).

Or at the very least just support webpack 4 and below and provide bug fixes but no new features.

@cap-Bernardito or @evilebottnawi do you have any feedback to give regarding this? 
Does it make sense or are there any use cases where [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) cloud be useful in webpack 5?

**Comment by evilebottnawi** [comment]
@NMFR Hello, I think no, also the two plugins can be confusing in the long term so I would be glad if we focused on one plugin, if you want to help or do some improvements write issue(s) and we will do it, feel free to deprecate it in favor `css-minimizer-webpack-plugin`
