### ISSUE TITLE
use this plugin with warning in webpack5， due to refer last-call-webpack-plugin？

### ISSUE THREAD

**Issue by mingyuyuyu** [NMFR/optimize-css-assets-webpack-plugin#138]
[DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
     at compiler.hooks.compilation.tap (d:\BGGIT\dev\applications\banggood\templates\black\web\node_modules\last-call-webpack-plugin\src\index.js:176:49)

**Comment by NMFR** [comment]
As it is stated in the README:
> ⚠️ For webpack v5 or above please use css-minimizer-webpack-plugin instead.

More info on https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/134
