### ISSUE TITLE
build failed with unicode-range wildcard format

### ISSUE THREAD

**Issue by yuecchen** [NMFR/optimize-css-assets-webpack-plugin#141]
with the following css code, webpack build will throw `semicolon missing` exception. 

```
unicode-range:u+00??,u+0131,u+0152-0153,u+02bb-02bc,u+02c6,u+02da,u+02dc,u+2000-206f,u+2074,u+20ac,u+2122,u+2191,u+2193,u+2212,u+2215,u+feff,u+fffd
```

**Comment by NMFR** [comment]
Should be a cssnano issue, just updated the cssnano (default processor) version. This should be solved.
