### ISSUE TITLE
used with webpack5

### ISSUE THREAD

**Issue by romanown** [NMFR/optimize-css-assets-webpack-plugin#143]
when i to try installed it i have error.
npm install --save-dev optimize-css-assets-webpack-plugin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: svelte-app@1.0.0
npm ERR! Found: webpack@5.24.2
npm ERR! node_modules/webpack
npm ERR! dev webpack@"^5.16.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from optimize-css-assets-webpack-plugin@5.0.4
npm ERR! node_modules/optimize-css-assets-webpack-plugin
npm ERR! dev optimize-css-assets-webpack-plugin@"*" from the root project

**Comment by kolka199972** [comment]
Including update to webpack 5.
Some things are probably opinionated.

Replaced optimize-css-assets-webpack-plugin with css-minimizer-webpack-plugin

**Comment by NMFR** [comment]
As it is stated in the README:

⚠️ For webpack v5 or above please use css-minimizer-webpack-plugin instead.

More info on #134
