### ISSUE TITLE
A problem of 'stripWWW' configuration option in plugin 'postcss-normalize-url'

### ISSUE THREAD

**Issue by panricas** [NMFR/optimize-css-assets-webpack-plugin#15]
If the font resource is referenced in the css file, there is a problem with the url of font resource in the dist package file, the url is without 'www', like this '//abc.com'. It will lead to the failure of reference of font resource. So I think you should expose a configuration item in the optimize-css-assets-webpack-plugin to set the option 'stripWWW' in plugin 'postcss-normalize-url'.

**Comment by NMFR** [comment]
The CSS manipulation is delegated to `cssnano` (the default) or the provided `cssProcessor`.

I believe this is a `cssnano` configuration issue.
Your can control the config via the `cssProcessorOptions` property.

**Comment by panricas** [comment]
@NMFR: Thanks for your answer.It worked.
