### ISSUE TITLE
[Bug] is it a break change v5.0.5?

### ISSUE THREAD

**Issue by SoloJiang** [NMFR/optimize-css-assets-webpack-plugin#155]
Before this version, the plugin works well with webpack4, but now it updated postcss to v
8 which only can work with webpack5. The change has maked our projects build failed.

**Comment by NMFR** [comment]
Why is postcss not compatible with webpack5?
Our unit tests seem to be all green with webpack4.

It can however be a node.js version. What version are you on?

**Comment by ferrao** [comment]
I have the same issue @NMFR, I am running node 12.22.1 and npm 6.14.12

This is a breaking dependency and it is actually breaking the default install of the [Phoenix Framework](https://github.com/phoenixframework/phoenix/issues/4331)

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/118421171-26d91080-b6f3-11eb-8caa-99c9af9af58b.jpeg)

**Comment by NMFR** [comment]
Should be fixed in 5.0.6.

Released: 
- 5.0.6 with a revert of the cssnano and postcss major upgrade.
- 6.0.0 with the cssnano and postcss major upgrade.

Reopen if there are still problems on 5.0.6 please.
