### ISSUE TITLE
[6.0.0] PostCSS missing due to incorrect identification as peerDependency 

### ISSUE THREAD

**Issue by johnhunter** [NMFR/optimize-css-assets-webpack-plugin#159]
This may not be an issue with `optimize-css-assets-webpack-plugin` itself.

On upgrading from `5.0.4` to `6.0.0` webpack builds fail due to a missing `postcss@8` dependency. This is odd because it is a dependency in the packable.json (confirmed in the installed package in node_modules). However `npm ls postcss` reports it as an unmet peer dependency. A workaround is to install it as a peer, but that shouldn't be necessary as it is already a dependency.

- Webpack 4
- npm 6.14.12
```
[webpack-cli] Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
```

**Comment by bendvc** [comment]
I'm seeing the same issue. I'm currently upgrading from `5.0.6` to `6.0.1` due to a vulnerability in a transitive dependency (normalize-url) and i'm being left with the following error: 
```
├─┬ optimize-css-assets-webpack-plugin@6.0.1
│ └── UNMET PEER DEPENDENCY postcss@8.3.5 
```

@johnhunter were you able to resolve your issue?

**Comment by johnhunter** [comment]
The way I resolved it was to add `postcss` as a top level dependency. I've since upgraded to `optimize-css-assets-webpack-plugin@6.0.1`. Just checked now and removing the `postcss` top level dependency has not caused the issue to recur but I've not tested in on CI yet.

**Comment by johnhunter** [comment]
Stale issue. Closing.
