### ISSUE TITLE
Source map always points to single file with complicated webpack config

### ISSUE THREAD

**Issue by shkarupa-alex** [NMFR/optimize-css-assets-webpack-plugin#16]
I've got 2 sources of css: .css and .scss
For both of them i have such loaders with extraction:
```javascript
{
  test: /\.css$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: {importLoaders: 1, minimize: false, sourceMap: true},
      },
      {
        loader: 'postcss-loader',
        options: {sourceMap: true},
      },
    ],
  }),
},
{
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: {minimize: false, sourceMap: true},
      },
      {
        loader: 'postcss-loader',
        options: {sourceMap: true},
      },
      {
        loader: 'sass-loader',
        options: {
          outputStyle: 'expanded',
          sourceMap: true,
        },
      },
    ],
  }),
},
```

Then i have such optimize plugin exec:
```javascript
new OptimizeCssAssetsPlugin({
  cssProcessor: require('cssnano'),
  cssProcessorOptions: {
    preset: 'default',
    map: {inline: false},
  },
}),
```

After all if i try to choose some node in Chrome DevTool, styles always point to one file https://www.evernote.com/l/AS84t-O36W5PGIklf_An0IpJiU61MUuuo14
But in most cases it is wrong.

**Comment by NMFR** [comment]
Think this is a `ExtractTextPlugin` problem.

Are you including the `ExtractTextPlugin` plugin with a static name or dynamic?

``` javascript
webpackPlugins.push( // webpack config module.exports.plugins
  new ExtractTextPlugin('[name].css')
);
```

If you remove the `OptimizeCssAssetsPlugin` plugin, every thing works as expected?

**Comment by yarthur** [comment]
I've been experiencing much the same thing. 
Config (bits that I think are important):
```
{
  test: /\.css$/,
  use: ExtractTextWebpackPlugin.extract({
    fallback: "style-loader",
    use: [
      {
        loader: "css-loader",
        options: {
          importLoaders: 1,
          sourceMap: true
        }
      },
      {
        loader: "postcss-loader",
        options: {
          sourceMap: true
        }
      }
    ]
  })
}
```
and
```
plugins: [
  new ExtractTextWebpackPlugin({
    filename: "bundled.css",
    publicPath: "/public/css",
    allChunks: true
  }),
  // Call the css minification
  new OptimizeCSSAssets({
      cssProcessorOptions: { sourceMap: true }
  })
]
```

All styles would point to line 1 of the same file (which would not be "bundled.css").

Commenting out the OptimizeCSSAssets plugin declaration resulted in a useful source map.

**Comment by shkarupa-alex** [comment]
I wanted to make a PR, but with last-call-plugin it was impossible to solve this issue because there are no access to other assets during transformation.

So i write my own plugin https://github.com/intervolga/optimize-cssnano-plugin

**Comment by NMFR** [comment]
I believe the problem is solved in version `v3.1.0`.

Can you confirm?

**Comment by NMFR** [comment]
Closing the issue due to inactivity.

Please let me know if there are still problems with this and i will reopen.

**Comment by shkarupa-alex** [comment]
Unfortunately, issue is still active

**Comment by NMFR** [comment]
Can you provide some code to replicate the issue?

**Comment by shkarupa-alex** [comment]
You can check out **first** test in my hand-crafted plugin https://github.com/intervolga/optimize-cssnano-plugin/blob/master/test/index.js

There is original source map an it updated while applying cssnano
Try to replace "new Plugin" in test config https://github.com/intervolga/optimize-cssnano-plugin/blob/master/test/helpers/generate-config.js with optimize-css-assets-webpack-plugin and see what happens with paths in source map

**Comment by NMFR** [comment]
Seems to be working correctly. I replaced your plugin usage (`Plugin` in line 68) of [generate-config.js](https://github.com/intervolga/optimize-cssnano-plugin/blob/master/test/helpers/generate-config.js) with:

``` javascript
new OptimizeCssAssetsPlugin({
  assetNameRegExp: /\.css$/g,
  cssProcessorOptions: {
    discardComments: {
      removeAll: true,
    },
    map: {
      inline: false,
    },
  },
  canPrint: true,
}),
```

And the CSS seems to have the correct source mapping `/*# sourceMappingURL=produced.css.map */`. The test failed because we are using different versions of cssnano that generate slightly different CSS (i noticed a difference in CSS color `blue` !== `#00f`).

Or did i miss something else?

**Comment by shkarupa-alex** [comment]
You're right, it's working now.
Found small issue in postcss-loader. It should be declared as 
```javascript
{
  loader: 'postcss-loader',
    options: {
      sourceMap: 'inline',
    },
},
```
With sourceMap=true it miss paths to css files.

The last small problem is removing source map. If i set cssProcessorOptions.map=false - source map emmited anyway. Old source map i think.
Except this problem issue solved.

**Comment by NMFR** [comment]
I am not quite understanding the remaining issue.

If you set `cssProcessorOptions.map` to false it means the optimization process that `optimize-css-assets-webpack-plugin` runs will not generate source maps but if the original config does (`postcss-loader`) the .map file will still be generated (by `postcss-loader`) but it will be wrong because `optimize-css-assets-webpack-plugin` has modified the CSS.

This means `postcss-loader` and `cssProcessorOptions` source map config must be synced (both enabled or disabled) or else inconsistent .map files will be generated.

**Comment by NMFR** [comment]
I think this is solved, please comment if it isn't so the issue can be reopened.
