### ISSUE TITLE
PostCSS 8 breaking change in 5.0.7

### ISSUE THREAD

**Issue by kyletsang** [NMFR/optimize-css-assets-webpack-plugin#167]
Same as #155 

5.0.7 brought back PostCSS 8 which is breaking our builds.

**Comment by holidaypenguin** [comment]
I want to go online

**Comment by xiaoSais** [comment]
Same problem, any one can solve it?

**Comment by holidaypenguin** [comment]
> Same problem, any one can solve it?

5.0.3

**Comment by zhangyuang** [comment]
watch it

**Comment by holidaypenguin** [comment]
"optimize-css-assets-webpack-plugin": "<=5.0.3",

**Comment by timocov** [comment]
It seems that the new patch release includes updating of major versions of dependencies v5.0.4...aaa1395. Is it possible to unpublish/deprecate 5.0.7 version (or maybe release 5.0.8 with the old dependencies) and release the current state as the next major version?

**Comment by seanlandsman** [comment]
Pinning "optimize-css-assets-webpack-plugin": "5.0.6" fixed this issue for me

**Comment by NMFR** [comment]
Should be fixed in 5.0.8
