### ISSUE TITLE
Problem in the dependency chain

### ISSUE THREAD

**Issue by ielgnaw** [NMFR/optimize-css-assets-webpack-plugin#169]
There is a problem with the `css-declaration-sorter` in the dependency chain

**version 5.0.7**

![wecom-temp-9b2cbdbbee48414470d88015d11e43b4](https://user-images.githubusercontent.com/1153430/123028974-ea47b580-d412-11eb-8485-fc98d0956784.png)

**Comment by NMFR** [comment]
Should be fixed in 5.0.8
