### ISSUE TITLE
Does not seem to work with WebpackCompressionPlugin

### ISSUE THREAD

**Issue by pmnc-philippe** [NMFR/optimize-css-assets-webpack-plugin#17]
hello,
Great plugin ! I have an issue : it does not work with WebpackCompressionPlugin. The compression plugin works fine but the file being compressed is not the file before calling optimize-css-assets-webpack-plugin. This is probably because optimize-css-assets-webpack-plugin uses last-call-webpack-plugin to process the css file at the very last moment, just before emitting to the file - and so compression does not see it. 
I am not knowledgeable in architecture of webpack plugin but it seems to be a flaw in optimize-css-assets-webpack-plugin. what else do you think, let me know if you have any plan to fix it ?

**Comment by NMFR** [comment]
Both plugins seem to use the same event `optimize-assets` to process the asset. I wonder if changing the order of the plugins in the plugins array will fix it.

Can you provide me with a code sample to test the issue please?

**Comment by NMFR** [comment]
Should be working in version 3.2.0
