### ISSUE TITLE
PostCSS plugin postcss-discard-comments requires PostCSS 8.

### ISSUE THREAD

**Issue by xingyongchao** [NMFR/optimize-css-assets-webpack-plugin#170]
PostCSS plugin postcss-discard-comments requires PostCSS 8.

**Comment by seanlandsman** [comment]
I get the same error when doing Gatsby builds - tying the dependency to 5.0.6 allows me to continue

**Comment by timocov** [comment]
It seems that the new patch release includes updating of major versions of dependencies https://github.com/NMFR/optimize-css-assets-webpack-plugin/compare/v5.0.4...aaa1395756e9be5dac8965076b9e3ab39fff5832. Is it possible to unpublish/deprecate 5.0.7 version (or maybe release 5.0.8 with the old dependencies) and release the current state as the next _major_ version?

**Comment by timocov** [comment]
Duplicate of #167

**Comment by NMFR** [comment]
Should be fixed in 5.0.8
