### ISSUE TITLE
Whole number trailing zeros are removed

### ISSUE THREAD

**Issue by rynocouse** [NMFR/optimize-css-assets-webpack-plugin#21]
Trailing zeros are striped from whole numbers.

**input**:` z-index: 6000;`
**expected**: `z-index: 6000;`
**actual**: `z-index: 6;`

**Comment by NMFR** [comment]
The CSS manipulation is delegated to the `cssProcessor` (`cssnano` by default), check what `cssnano` options you can use to control that transformation. You can pass `cssnano` options in the `cssProcessorOptions` property.
