### ISSUE TITLE
Remove css-nano dependecy

### ISSUE THREAD

**Issue by radeno** [NMFR/optimize-css-assets-webpack-plugin#24]
Hi,

this module have really nice idea, because css-loader could not minify CSS files.
If this module allows to choose custom minifier (cssnano or other like cleancss) then i think cssnano could not be defined as dependency. It could be removed (someone want to use version 4 etc) or moved to peerDependency.

In both ways are not cssnano installed by default so there is no dependency hell.

**Comment by NMFR** [comment]
This discussion already happened [here](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/11).

The most common usage of this plugin will be with the default settings. Moving cssnano dependency to peer dependencies or removing it altogether would hurt the most common use case (95% of people would be force to do more config and installs just to get this working). People would have to install cssnano and there would be the possibility to have version conflicts.

If you really can't live with the dependency to cssnano this [response](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/11#issuecomment-317281600) should give you an alternative
