### ISSUE TITLE
keyframes not working

### ISSUE THREAD

**Issue by vinaySaxo** [NMFR/optimize-css-assets-webpack-plugin#25]
my css code including keyframes someAnimation{....} is not showing up in compressed css file after applying optimize-css-assets plugin. It is working fine in development mode with just ExtractTextPlugin plugin

**Comment by NMFR** [comment]
The CSS manipulation is done by `cssnano` by default. Could it be that if those keyframes aren't being used `cssnano` is removing them?

Check the config of `cssnano` to control the output CSS.
