### ISSUE TITLE
[Bug] plugin removes the www subdomain.

### ISSUE THREAD

**Issue by kumarrishav** [NMFR/optimize-css-assets-webpack-plugin#26]
while loading fonts, it url is https://www.foo.com/aaa.woff
then plugins removes the www from url. 

Input: https://www.foo.com/aaa.woff
output: https://foo.com/aaa.woff

expected: https://www.foo.com/aaa.woff

**Comment by NMFR** [comment]
This is most probably caused either by webpack configuration or cssnano configuration. This plugin does not manipulate CSS directly, it uses cssnano by default to process CSS.  

To help troubleshoot you should also check if the url is being mutated by this plugin (if it is you need to change the cssnano config of the plugin) or by your own CSS loaders.

**Comment by kumarrishav** [comment]
so, probably because of cssnano then. as, after removing optimize-css-assets-webpack-plugin, it is working fine.

**Comment by kumarrishav** [comment]
here is the config: https://github.com/ben-eb/gulp-cssnano/issues/44#issuecomment-210470810

Thanks.
