### ISSUE TITLE
Conflict between optimize-css-assets-webpack-plugin and autoprefixer

### ISSUE THREAD

**Issue by sfengx** [NMFR/optimize-css-assets-webpack-plugin#27]
How to configure like '{"autoprefixer": {browsers: ['iOS >=8', 'Android >= 4.1']}}'

**Comment by NMFR** [comment]
By default cssnano is used to process CSS. You can configure cssnano in the `cssProcessorOptions` parameter.

**Comment by sfengx** [comment]
thanks
