### ISSUE TITLE
optimize-css-assets-webpack-plugin along with css split plugin

### ISSUE THREAD

**Issue by didi0613** [NMFR/optimize-css-assets-webpack-plugin#28]
Hi,
We've recently seeing an issue when optimizing the css assets along with the css split plugin.

The `optimize-css-assets-webpack-plugin` requires the `last-call-webpack-plugin` and it will optimize the css at the final step after the css got split. 

This causing an issue if we have specified z-index in each of the split css files, z-index will get reduction by optimization at the final step (after the css got split) and affects the render. What are we expected is that optimize the code first and split later. (Somehow last call webpack plugin always comes to the last)

Can we add a customized option way to specify the start/end of the execution of the css optimization based on these two lines here: https://github.com/NMFR/last-call-webpack-plugin/blob/master/index.js#L38-L39
OR
Please let me know if there is a better way to control the order of the plugins.

Thank you very much in advance!

**Comment by didi0613** [comment]
Update:
This prob related to the cssnano issue: https://github.com/ben-eb/gulp-cssnano/issues/8
Question, when can we update the dependency to v4.0.0

**Comment by didi0613** [comment]
Update:
The problem got resolved by enabling safe option to true.
It will disable z-index from reduction by css optimization

**Comment by NMFR** [comment]
The CSS manipulation of this plugin is delegated to cssnano. I see you have found the cssnano configuration to control your z-index issue :)

Regarding supporting cssnano v4.0.0, i don't think v4.0.0 is ready yet (still in release candidate state). When cssnano finalizes v4.0.0 we will upgrade.

**Comment by vipcxj** [comment]
This is really a big problem. I found a lot of issue relate to this. For example autoprefixer is enabled by default in v3, but it can not accept the proper browser list config. As a result it remove useful css. All these can be fixed by update to v4

**Comment by adeelibr** [comment]
any updates?

**Comment by NMFR** [comment]
I am still waiting for the final release of cssnano v4 to come out.

If you really can't wait install the version of cssnano you want and pass it as the cssProcessor:

```
npm i -S cssnano@4.0.0-rc.2
```

and 

```
new OptimizeCssAssetsPlugin({
  cssProcessor: require('cssnano'),
  cssProcessorOptions: { discardComments: { removeAll: true } }
})
```
