### ISSUE TITLE
the generated sourcemappingUrl doesn't point to a map file 

### ISSUE THREAD

**Issue by chhaymenghong** [NMFR/optimize-css-assets-webpack-plugin#33]
Instead it is as followed ( which increase the bundle size):

Example:
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm1haW4uOTU3NDljODRjYzU0NzNiNTdiZjY3ZWQ2OTU4Y2Y1YjQuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUNBLE1BQ0ksaUJBQW1CLENBQ3RCIiwiZmlsZSI6Im1haW4uOTU3NDljODRjYzU0NzNiNTdiZjY3ZWQ2OTU4Y2Y1YjQuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLypzZGZzZGYqL1xuI3Rlc3Qge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbn1cbiJdfQ== */

**Comment by NMFR** [comment]
Sorry for the delay in answering.
Lately i haven't had much time to solve issues but i intend to work on them in the next weekend.
Can you provide a code sample to replicate the issue please?

**Comment by NMFR** [comment]
Just tested source map generation (either inline and on a separate file) and it seems fine.

Without a way to replicate the problem i will close this issue.

If you still have this problem please provide a code base to replicate the problem and i will reopen this issue.
