### ISSUE TITLE
anticipated changes needed for webpack v4 support?

### ISSUE THREAD

**Issue by thescientist13** [NMFR/optimize-css-assets-webpack-plugin#34]
Wondering if any changes will be needed for v4?
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

Likely `this.option`?

I know that [`ExtractTextWebpackPlugin` is still awaiting v4 support](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701)

Is there any plan for an upgrade?  Any pointers for someone to contribute it?  Thanks for the great work on this plugin!  🙏 ✌️

**Comment by NMFR** [comment]
A quick glance of the changes makes me believe the plugin should still run on webpack v4 (although i didn't test it yet) but webpack will probably emit deprecation warnings.

Must likely we need to change [`last-call-webpack-plugin`](https://github.com/NMFR/last-call-webpack-plugin)s implementation to completely conform with v4 plugin system changes (`optimize-css-assets-webpack-plugin` uses `last-call-webpack-plugin` dependency to interact with webpack bundle pipeline).

Lately i haven't had much time to solve issues but i intend to work on them in the next weekend. 
We are open to PRs if you wish to contribute :) 
For this issue the changes should start on `last-call-webpack-plugin` repo.
[`last-call-webpack-plugin`](https://github.com/NMFR/last-call-webpack-plugin) allows to process webpack assets, just give it a RegEx (to filter what assets to process) and a process function.
`last-call-webpack-plugin` should be changed to conform with webpack v4 plugin system changes.

Thanks for the support :)

**Comment by thescientist13** [comment]
Great, thanks for the feedback @NMFR !  Will try and take a look this week 👍 

Oh, I've been looking into helping out another plugin too, and writing some unit tests for them first before making the upgrade.  Would you be opposed to that here as a separate, preliminary PR?  I don't taking that on with a little help if need be.

**Comment by NMFR** [comment]
For tests see issue https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/31 

I believe some base work was started.

**Comment by tyscorp** [comment]
I can confirm that `optimize-css-assets-webpack-plugin` errors in webpack v4. I seem to get 'Unknown word' for everything. Logging the css passed to `cssnano.process` logs a JavaScript chunk, not CSS.

**Comment by thescientist13** [comment]
thanks @NMFR will do!

**Comment by mjprude** [comment]
Hey @thescientist13 we've started work on testing this plugin [here](https://github.com/cnerepo/optimize-css-assets-webpack-plugin/pull/1/) and are iterating on that as time permits to get it into a fully PRable state.
We'd welcome contributions (see the unchecked items) but it might make more sense to start with the `last-call-webpack-plugin` as @NMFR suggested. Be in touch if you do start working on tests (or see an issue in tests with the v4 migration) so we don't end up duplicating work. Thanks!

**Comment by NMFR** [comment]
I just released `optimize-css-assets-webpack-plugin@4.0.0` supporting the new webpack v4 plugin API.

PS: I did some small tests on `optimize-css-assets-webpack-plugin@3.2.0`  and besides the deprecation warning the plugin seemed to work correctly with webpack v4.

**Comment by thescientist13** [comment]
Thanks @NMFR !

**Comment by thescientist13** [comment]
I just tested and all is looking good in my project!  thanks for the great work on this plugin!  🙏 🎉
