### ISSUE TITLE
Doesn't work with webpack 4 ?

### ISSUE THREAD

**Issue by JeanBarriere** [NMFR/optimize-css-assets-webpack-plugin#36]
Hi,

I am currently upgrading a project based on the pwa vue template to webpack4, and it uses this plugin in the building process.
But the plugin is generating the error : `CssSyntaxError: XXX.css:X:X: Missed semicolon`
NB: I'm assuming the plugin is generating it as there is no error through my compilation when I disable it.

The PWA configuration of the plugin is the following:
```javascript
new OptimizeCSSPlugin({
  cssProcessorOptions: {
    safe: true
  }
})
```

Sources: [PWA vue template](https://github.com/vuejs-templates/pwa)

**Comment by NMFR** [comment]
I just released `optimize-css-assets-webpack-plugin@4.0.0` supporting the new webpack v4 plugin API.

I did some small tests on `optimize-css-assets-webpack-plugin@3.2.0`  and besides the deprecation warning the plugin seemed to work correctly with webpack v4.

If the issue persists please let me know and i ll reopen the issue.
