### ISSUE TITLE
Invalid stat.json when using plugin

### ISSUE THREAD

**Issue by Alex-Sokolov** [NMFR/optimize-css-assets-webpack-plugin#4]
**What is the current behavior?**
Invalid stat.json, file start wth:
```

Starting to optimize CSS...
Processing bundle.css...
Processed bundle.css, before: 327621, after: 265824, ratio: 81.14%
{
  "errors": [],
  "warnings": [
...
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- run `set NODE_ENV=production&& webpack --profile --json > stats.json`

**What is the expected behavior?**
Expected correct stat.json

Using:
- webpack 2.2.0
- extract-text-webpack-plugin 2.0.0-beta.5
- optimize-css-assets-webpack-plugin 1.3.0

**Comment by NMFR** [comment]
I haven't had time to updated optimize-css-assets-webpack-plugin to work with webpack 2.

I will try to see if i have the time in the next weekend.

**Comment by NMFR** [comment]
Ok, it seems that this plugin already works correctly in webpack 2 and no changes are required.

What you want is for the plugin not to print any messages.
You can configure this by setting the '**canPrint**' option to false:

``` javascript
var OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
module.exports = {
  ...otherWebpackOptions,
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new OptimizeCssAssetsPlugin({
      ...someOtherOptions,
      canPrint: false
    })
  ]
}
```

Close the issue if this solved it please.

**Comment by Alex-Sokolov** [comment]
Thanks for answer!

But maybe better use `this.options.canPrint && console.warn()` for console messages instead of `self.print`?
This is how messages logged by [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) for example and their prints not get into json

**Comment by NMFR** [comment]
I am not quite understanding the advantage.

The only difference is we use console.log instead of console.warn.
Otherwise ``` self.print ``` ends up doing the equivalent of your suggestion:

``` javascript
OptimizeCssAssetsPlugin.prototype.print = function() {
  if (this.options.canPrint) {
    console.log.apply(console, arguments);  
  }
};
```

**Comment by NMFR** [comment]
Ok, after re reading your suggestion i understand.

What you really want is our default value of ``` canPrint ```to be less intrusive and assume a value of false if not set. 

Maybe you are right. But i can't find a strong argument to change it, unless the majority of people use the --json option on webpack. But if that was the case the --json option of webpack would be the default and if you didn't want a json response you would have to specify it.

**Comment by Alex-Sokolov** [comment]
Oh. Ok, I didn't see that `self.print` using `console` inside :))) Thanks for explanation!
Just trying to understand what the difference in others plugins, which messages not added to json :)
