### ISSUE TITLE
How about update the version of cssnano?

### ISSUE THREAD

**Issue by ZhangPingFan** [NMFR/optimize-css-assets-webpack-plugin#40]
I found a problem like [https://github.com/ben-eb/cssnano/issues/357](url) and it's fixed in cssnano v4.0.0,so how about update it?

**Comment by NMFR** [comment]
I am waiting for the final v4 of cssnano to upgrade. Right now there are only release candidate versions available for cssnano v4.

If you really really need to control the cssnano version you can install the version you want and pass it in the `cssProcessor` option or take a look at [this issue](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/11#issuecomment-317281600) to have more control about the dependencies that get installed.
