### ISSUE TITLE
Animation name is minimized

### ISSUE THREAD

**Issue by Shenmin-Z** [NMFR/optimize-css-assets-webpack-plugin#44]
I have the following CSS animation:

`animation: fa-spin 1s infinite steps(8);`

It seems that after the minimization, it became:

`animation: a 1s infinite steps(8);`

and now the animation doesn't work.

**Comment by NMFR** [comment]
By default the CSS manipulation that this plugin does is delegated to `cssnano`. You can control the `cssnano` config in the `cssProcessorOptions` option.

You should be able to control this with `cssnano` options.

**Comment by leonardofaria** [comment]
@Shenmin-Z I had the same problem and I solved by using the safe mode:

```js
new OptimizeCSSAssetsPlugin({
  cssProcessorOptions: {
    safe: true,
  },
}),
```

**Comment by Shenmin-Z** [comment]
Thanks! It works!
