### ISSUE TITLE
What's the difference with the css-loader's minimize option

### ISSUE THREAD

**Issue by yangmingshan** [NMFR/optimize-css-assets-webpack-plugin#45]
css-loader provide a minimize option to minimizes the css, it also use cssnano-based minifier.
Is there difference with this plugin? Or they are the same?

**Comment by NMFR** [comment]
`css-loader' minimizes the CSS of the chunk. If you use `extract-text-webpack-plugin` or something similar to merge all the chunks together into a single CSS file the chunks are minimized / optimized individually but the sum of the chunks are not optimized and will probably have duplicated rules. 

Example:
  chunk.a.css:
    ```
    body { color: red; } a { color: blue; } 
    ```

  chunk.b.css:
    ```
    body { color:red; width: 100%; } a { font-size: 14px; } 
    ```

  extract-text-webpack-plugin.a.and.b.merged.css:
    ```
    body { color: red; } a { color: blue; } body { color:red; width: 100%; } a { font-size: 14px; }  
    ```

In the example you can see that chunks `a` and `b` are indeed optimized and minimized but if you just add them together you have two `body` rules duplicated and both of them setting the color to red. This gets aggravated if you import other CSS in your chunks, imagine that chunks `a` and `b` both import `font-awesome`, you will have `font-awesome` CSS duplicated in the final CSS. 

`optimize-css-assets-webpack-plugin` will fix this by minimizing / optimizing the final CSS files.
