### ISSUE TITLE
After going to the 4.0.0 version occures an error.

### ISSUE THREAD

**Issue by Valeronlol** [NMFR/optimize-css-assets-webpack-plugin#46]
node_modules/last-call-webpack-plugin/src/index.js:170
    compiler.hooks.compilation.tap(
                   ^
TypeError: Cannot read property 'compilation' of undefined

On version 3.2.0 everything works fine.

**Comment by NMFR** [comment]
Version 4 of the plugin requires `webpack` v4.

See issue #38.
