### ISSUE TITLE
How to keep `-webkit-box-orient` 	property ?

### ISSUE THREAD

**Issue by kmvan** [NMFR/optimize-css-assets-webpack-plugin#47]
css content:
```
div {
  /* autoprefixer: off */
  -webkit-box-orient: vertical;
  /* autoprefixer: on */
}
```

options:
```
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorOptions: {
        discardComments: { removeAll: false }, // or removeAll: true
      },
      canPrint: true,
    }),
```

After complite the `-webkit-box-orient` will be deleted. Can I keep it in css?

**Comment by NMFR** [comment]
By default the CSS manipulation that this plugin does is delegated to cssnano. You can control the cssnano config in the `cssProcessorOptions` option.

This is a cssnano related issue.
