### ISSUE TITLE
Does it supports sourcmap?

### ISSUE THREAD

**Issue by zhaoyao91** [NMFR/optimize-css-assets-webpack-plugin#5]
after I add this plugin, I can't use sourcemap to locate the source file in chrome.

**Comment by NMFR** [comment]
This plugin does not touch any CSS, it delegates that to the CSS processor (cssnano by default or the processor in the "cssProcessor" option).

So its up to that processor to generate sourcemaps.

Try setting the sourcemap option of cssnano (you can set the CSS processor options with the "cssProcessorOptions" option).

Example:

``` javascript
var OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
module.exports = {
    module: {
        loaders: [
            { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") }
        ]
    },
    plugins: [
        new ExtractTextPlugin("styles.css"),
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.optimize\.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorOptions: { sourcemap: true },
      canPrint: true
    })
    ]
}
```

Bear in mind that this plugin's input will likely be a processed CSS asset that already has a sourcemap, if so the CSS processor must take that into account to generate a correct sourcemap.

**Comment by NMFR** [comment]
Seems i was wrong, there was something missing to correctly generate source maps on our end.

This was fixed by https://github.com/NMFR/optimize-css-assets-webpack-plugin/pull/6

Please try the new version (1.3.1).

If you want an example how to get source maps working with this plugin checkout our "tests" branch.

**Comment by avesus** [comment]
https://github.com/postcss/postcss/blob/master/docs/source-maps.md
