### ISSUE TITLE
Critical - Command Injection

### ISSUE THREAD

**Issue by MichaelFBA** [NMFR/optimize-css-assets-webpack-plugin#50]
When doing an `npm audit`

It says not to use this plugin because of its deep deps on macaddress

https://nodesecurity.io/advisories/654

```
Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ optimize-css-assets-webpack-plugin [dev]                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ optimize-css-assets-webpack-plugin > cssnano >               │
│               │ postcss-filter-plugins > uniqid > macaddress                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654
```

**Comment by luizgrs** [comment]
https://github.com/scravy/node-macaddress/issues/19

They are trying to find someone to accept the PR...

**Comment by NMFR** [comment]
Seems that `postcss-filter-plugins` dropped the dependency with the vulnerability in version `3.0.1` but `cssnano` does not have this updated in any stable release.

**Comment by pldg** [comment]
Update `cssnano` solve the problem, `macaddress` is no more a dependency (try search for it in node_modules)

**Comment by pldg** [comment]
@NMFR Version 3.10.0. Try to run `npm i -D cssnano`, should solve the problem. To check for vulnerability use `npm audit`, also manually search `macaddress` in *node_modules*
