### ISSUE TITLE
It remove browser prefix by default, but I want to save prefix when generate css files.

### ISSUE THREAD

**Issue by ansenhuang** [NMFR/optimize-css-assets-webpack-plugin#51]

**Comment by ansenhuang** [comment]
So what can I do ?

**Comment by zhangolve** [comment]
me too.

**Comment by ansenhuang** [comment]
I finded the solution, we can pass by some option to cssnano, please view following example:

```js
new OptimizeCssAssetsPlugin({
    assetNameRegExp: /\.css$/g,
    cssProcessorOptions: {
      safe: true,
      autoprefixer: { disable: true },
      mergeLonghand: false,
      discardComments: {
        removeAll: true
      }
    },
    canPrint: true
  });
```

the option of `autoprefixer: { disable: true }` will disable cssnano's autoprefixer and saved prefixer that already exist by ourselves.

**Comment by blue-lightning** [comment]
While [ansenhuang's answer](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/51#issuecomment-394263867) is correct, if you want to only disable Autoprefixer's remove outdated prefixes function and keep everything else, replace `disable: true` with `remove: false`.
