### ISSUE TITLE
Fails to merge properties for a selector with other styles present

### ISSUE THREAD

**Issue by Streemo** [NMFR/optimize-css-assets-webpack-plugin#52]
**Edit: See final update below.**

a.css
```
#root {
  background-color: #f00;
}
body {
  text-align: center;
}
```
b.css
```
#root {
  width: 640px;
  height: 360px;
}
```
expected.css
```
#root{width:640px;height:360px;background-color:red}body{text-align:center}
```
actual.css
```
#root{background-color:red}body{text-align:center}#root{width:640px;height:360px}
```

If the `body` style is omitted, it merges the `#root` styles as expected.

**Comment by Streemo** [comment]
If the `body` declaration is first, it works as expected:

```
body {
  text-align: center;
}
#root {
  background-color: #f00;
}
```

b.css
```
#root {
  width: 640px;
  height: 360px;
}
```

actual.css === expected.css
```
body{text-align:center}#root{background-color:red;width:640px;height:360px}
```

**Comment by Streemo** [comment]
If each declaration is in a separate file, it works as expected:

a.css
```
#root {
  background-color: #f00;
}
```

b.css
```
body {
  text-align: center;
}
```

c.css
```
#root {
  width: 640px;
  height: 360px;
}
```

actual.css === expected.css

```
#root{background-color:red;width:640px;height:360px}body{text-align:center}
```

**Comment by Streemo** [comment]
index.js
```
import "a.css"
import "b.css"
import "c.css"
```
will produce the offending output, whereas importing `a` and `c` consecutively (the `#root` declarations) produced the expected output:

```
import "a.css"
import "c.css"
import "b.css"
```

So, does order matter with these sheets, really? Shouldn't they be merged anyway? I think it would be a bit cumbersome to have to optimize the order of my imports if it can be done automatically.

**Comment by NMFR** [comment]
Will take a look in the weekend, but i suspect it is a `cssnano` issue.

**Comment by NMFR** [comment]
It seems this is the expected behaviour.

`cssnano` will only merge adjacent rules https://cssnano.co/optimisations/mergerules/
