### ISSUE TITLE
Anyway to set the outputted filename to use name when split?

### ISSUE THREAD

**Issue by 814k31** [NMFR/optimize-css-assets-webpack-plugin#57]
I'm having trouble getting the outputted filenames to be `bundle.css` and `vendor.bundle.css`

Currently I'm getting `bundle.css and 0.bundle.css` ONLY when minified despite having:
```
"webpack": "^4.5.0",
"webpack-cli": "^2.0.14",
```

```js
optimization: {
    splitChunks: {
        cacheGroups: {
            commons: {
                test: /[\\/]node_modules[\\/]/,
                name: 'vendor',
                chunks: 'all'
            }
        }
    },
    minimizer: [new OptimizeCSSAssetsPlugin({}), new UglifyWebpackPlugin({ sourceMap: true })]
},
```

**Comment by NMFR** [comment]
Are you sure that without `OptimizeCSSAssetsPlugin` this does not happen?

`OptimizeCSSAssetsPlugin` does not touch the file name.

**Comment by 814k31** [comment]
I just had another look and found out my build is using the chunk id instead of the chunk name
I'll look into this but as for now doesn't look like its related to this plugin

Minified:
<img width="745" alt="screen shot 2018-06-11 at 8 44 03 am" src="https://user-images.githubusercontent.com/9160551/41208309-b280fb66-6d54-11e8-90da-f3a312607cfd.png">

Non-minified
<img width="542" alt="screen shot 2018-06-11 at 8 46 15 am" src="https://user-images.githubusercontent.com/9160551/41208313-bd042e14-6d54-11e8-9d34-67b1b5bfd518.png">

Cheers for your help
