### ISSUE TITLE
Can update cssnano from 3.10 to 4.0?

### ISSUE THREAD

**Issue by ElvisWang27** [NMFR/optimize-css-assets-webpack-plugin#60]
I met this problem : https://github.com/cssnano/cssnano/issues/330 ,I need to resolve it with update cssnano

**Comment by frenzzy** [comment]
Have you tried to use `safe` mode? #58

**Comment by NMFR** [comment]
I am waiting for a final release of cssnano v4, it seems to still be in release candidate stage.

**Comment by ElvisWang27** [comment]
@frenzzy Thanks for help

**Comment by Hoolean** [comment]
[Looks like v4 has arrived](https://www.npmjs.com/package/cssnano).

Also afflicted by the z-index annoyance, would be great to enjoy their upstream fix :)

**Comment by NMFR** [comment]
See https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/63
