### ISSUE TITLE
Upgrade cssnano to v4

### ISSUE THREAD

**Issue by yangmingshan** [NMFR/optimize-css-assets-webpack-plugin#63]
[cssnano](https://github.com/cssnano/cssnano) v4 is released, is there a plan to upgrade it?

**Comment by NMFR** [comment]
Yes, will update it in the next weekend.

**Comment by NMFR** [comment]
Updated in https://github.com/NMFR/optimize-css-assets-webpack-plugin/commit/62ea898c0f7dba5d65e4c150c5047c79bfe29ffc.

Published in version [v5.0.0](https://github.com/NMFR/optimize-css-assets-webpack-plugin/releases/tag/v5.0.0).
