### ISSUE TITLE
it change my css code

### ISSUE THREAD

**Issue by joacycode** [NMFR/optimize-css-assets-webpack-plugin#67]
hi,
my css code is 
`.card-small-sku {
	width: 100%;
	height: 2.2rem;
	margin: .3rem auto;
	display: -webkit-box;
	display: -webkit-flex;
	display: flex;
	-webkit-box-align: center;
	-moz-align-items: center;
	-webkit-align-items: center;
	align-items: center;
	position: relative
}`
after webpack with using this plugin,it becomes likes this:
`.card-small-sku {
	width: 100%;
	height: 2.2rem;
	margin: .3rem auto;
	display: flex;
	-moz-align-items: center;
	align-items: center;
	position: relative
}`
this code lost some prefix that  want to fit  some browsers
what should i do , change some plugin params?

**Comment by NMFR** [comment]
The plugin uses `cssnano` as a `cssProcessor` by default. You can control the `cssnano` options via the `cssProcessorOptions` option.

``` javascript
    new OptimizeCssAssetsPlugin({
      cssProcessorOptions: { safe: true, discardComments: { removeAll: true } }
    })
```

Take a look at cssnano options (you probably want to control the autoprefixer options).
