### ISSUE TITLE
Wrong code example

### ISSUE THREAD

**Issue by bobahvas** [NMFR/optimize-css-assets-webpack-plugin#68]
Safe option was removed:

```
function parse(css, opts) {
    if (opts && opts.safe) {
        throw new Error('Option safe was removed. ' + 'Use parser: require("postcss-safe-parser")');
    }
    ...
}
```

Your example
```cssProcessorOptions: { safe: true, discardComments: { removeAll: true } },```

**Comment by ChiaJune** [comment]
have the exact same issue

**Comment by NMFR** [comment]
See https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/65
