### ISSUE TITLE
The v5 plugin API was not updated to support cssnano v4

### ISSUE THREAD

**Issue by jzempel** [NMFR/optimize-css-assets-webpack-plugin#69]
v5.0.0 was a breaking change in that it was [updated](https://github.com/NMFR/optimize-css-assets-webpack-plugin/commit/62ea898c0f7dba5d65e4c150c5047c79bfe29ffc) to depend on cssnano v4.0.2. However, this plugin was not updated to receive options per the [PostCSS 6.x breaking change](https://github.com/cssnano/cssnano/releases/tag/v4.0.0-rc.0) described by cssnano.

Please see https://cssnano.co/guides/presets/ for updated API details.

For example, attempt the following:

```js
new OptimizeCSSAssetsPlugin({
  cssProcessorOptions: { /* update API to receive a cssPluginOptions? */
    preset: [
      'default',
      {
        cssDeclarationSorter: false,
        normalizeWhitespace: false
      }
    ]
  }
});
```

Result: declarations will still be sorted and whitespace will be compressed by cssnano 4.

Reference:
* https://github.com/postcss/postcss/blob/master/CHANGELOG.md#60-marquis-orias
* http://api.postcss.org/postcss.html#.plugin vs. https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/v5.0.0/src/index.js#L62 ... 2nd parameter is `processOptions`; 3rd parameter is `pluginOptions`.

**Comment by rofrol** [comment]
To disable certain plugins, you need to do it in `package.json`:

```json
  "cssnano": {
    "preset": [
      "default",
      {"cssDeclarationSorter": {"exclude": true}}
    ]
  }
```

or in `postcss.config.js`:

```javascript
module.exports = {
    plugins: [
        require('cssnano')({
            preset: ['default', {
                cssDeclarationSorter: {
                    exclude: true,
                },
            }],
        }),
    ],
};
```

Disabling `webpack.config.js` or `cssnano.config.js` like descibed [here](https://cssnano.co/guides/presets/), doesn't work.

**Comment by jzempel** [comment]
I see what you're saying @rofrol. But your plugin's API could be updated to receive `cssPluginOptions`, right? If so, then it would continue to function in the manner it did prior to v5.0.0 where inlined options were applied to the cssnano transform.

**Comment by rofrol** [comment]
@jzempel It's not my plugin

**Comment by NMFR** [comment]
#73 solved this. 

If not tell me so i can reopen the issue.
