### ISSUE TITLE
source map url be removed after using discardComments

### ISSUE THREAD

**Issue by tangshuang** [NMFR/optimize-css-assets-webpack-plugin#7]
I want to output source map url in separated css file, and use settings like:

```
new OptimizeCssAssetsPlugin({
        cssProcessorOptions: {
          discardComments: {
            remove: comment => comment[0] !== '#',
          },
        },
      }),
```

However, after build, there is no sourcemap url in the final separated css.
Could you please check whether this works?

**Comment by NMFR** [comment]
This plugin does not touch CSS at all, it just delegates the CSS manipulation to the cssProcessor option (that's cssnano by default).

So i believe this is a cssnano configuration issue.

**Comment by tangshuang** [comment]
Thanks for replying.
Yes it is cssnano issue, but the true owner is postcss.
I find a way to fix:

```
cssProcessorOptions: {
          map: {
            inline: false,
          },
          discardComments: {
            remove: comment => comment[0] !== '#',
          },
        },
```

Pass `map.inline=false` into your plugin, which will be passed into cssnano and postcss to fix this issue.

**Comment by huibiaoli** [comment]
@tangshuang good job, but line number missing in source map in my case
