### ISSUE TITLE
can i ask a question

### ISSUE THREAD

**Issue by nicewahson** [NMFR/optimize-css-assets-webpack-plugin#74]
chunks duplicate means what? I cannot understand duplicate chunks

**Comment by NMFR** [comment]
Chunks will probably be duplicate free but when they are merged to generate a file (like what extract-text-webpack-plugin does) the merging can create duplicated rules.

chunk `A`:
`
body { color: red; }
a { color: blue; }
`

chunk `B`:
`
body { color: red; }
div { color: yellow; }
`

`A` and `B` merged:
`
body { color: red; }
a { color: blue; }
body { color: red; }
div { color: yellow; }
`

Chunks `A` and `B` do not have duplicated rules but if you simply merge them the body rule is duplicated.
