### ISSUE TITLE
discardComments removeall not working

### ISSUE THREAD

**Issue by joshuaavalon** [NMFR/optimize-css-assets-webpack-plugin#78]
I have a file that contains
```scss
// !!!
/*! ??? */
```

I have tried the following configs
```js
new OptimizeCSSAssetsPlugin({
  cssProcessorOptions: {
    map: { inline: false },
    discardComments: { removeAll: true },
  }
})
```
```js
new OptimizeCSSAssetsPlugin({
  cssProcessorPluginOptions: {
    preset: ['default', { discardComments: { removeAll: true } }],
  }
})
```
`/*! ??? */` still exists in the output file. I can confirm the plugin is working as the second config won't create a source map.

**Comment by NMFR** [comment]
By default the CSS processor used is cssnano. This means the issue is either a problem in the cssnano config or a bug on their side.
