### ISSUE TITLE
is it possible to disable/enable output minification ?

### ISSUE THREAD

**Issue by ctf0** [NMFR/optimize-css-assets-webpack-plugin#79]
i know that the package is all about optimizations but i was wondering if its possible to switch the output minify on/off, this is helpful in cases like
- test the output file size with & without the plugin.
- check if options like [mergerules](https://cssnano.co/optimisations/mergerules) is working correctly or not

**Comment by NMFR** [comment]
Can't you programmatically control if you add the plugin to webpack to achieve the same result?

Don't think it makes sense to have a noMinimize setting.
You can also check if cssnano has any setting like that.

**Comment by ctf0** [comment]
so far the only option that could get around the issue is `normalizeWhitespace` but i have tried to set it to false in both `cssProcessorOptions` & `cssProcessorPluginOptions` and no changes

also the one of the reasons i want to disable the minify from cssnano is i already have uglify which takes care of that.
