### ISSUE TITLE
issue related to css nano, maybe just a dependency upgrade?

### ISSUE THREAD

**Issue by kelly-tock** [NMFR/optimize-css-assets-webpack-plugin#83]
see https://github.com/cssnano/cssnano/issues/578#issuecomment-424773737

having issues with `calc(env(safe-area-inset-bottom) * 3` in css.

**Comment by bencripps** [comment]
+1 we're also having this issue

**Comment by kelly-tock** [comment]
this is now fixed if you update this plugin it will pick it up in css nano.
