### ISSUE TITLE
Removes important calculation brackets

### ISSUE THREAD

**Issue by muuvmuuv** [NMFR/optimize-css-assets-webpack-plugin#85]
I have one calculation made in a scss file:

```scss
                        ↧                                                ↧
  --text-xs: calc(1em / (var(--text-scale-ratio) * var(--text-scale-ratio)));
```

which _OptimizeCSSAssetsPlugin_ transforms to:

```scss
                       ↧                                                ↧
  --text-xs: calc(1em / var(--text-scale-ratio) * var(--text-scale-ratio));
```

this breaks the calculation and I get an unexpectet result in my styling.

Webpack configuration here: https://hastebin.com/alasininam.js
> If someone has any suggestions to optimize my webpack configuration please feel free to tell me 😁

**Comment by huhai122** [comment]
me too

**Comment by NMFR** [comment]
Should be a `cssnano` issue (if you are using the default processor).
`cssnano` version was updated in `v5.0.2`, check if this fixed it, if not please open an issue at `cssnano` github.
