### ISSUE TITLE
Doesn't work with css variables in calc

### ISSUE THREAD

**Issue by salim7** [NMFR/optimize-css-assets-webpack-plugin#88]
I get the following error when using css variables / custom properties in calc:
  `box-shadow: 0 0 0 calc((32px - var(--material-range-thumb-size)) / 2) var(--material-range-thumb-color);`

Error:
```
JisonParserError: Parse error on line 1: 
- var(--ipho...
--^
Expecting "SUB", "NUMBER", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "css_value", got unexpected "FUNCTION"
```

**Comment by AmaxJ** [comment]
Also running into this issue.

**Comment by bigmeow** [comment]
me too

**Comment by takuma7** [comment]
Same here

**Comment by githubSiYao** [comment]
me too. In .css File.， clac()  is Error

**Comment by acexyf** [comment]
me2, how can i solve this problem

**Comment by lensbart** [comment]
I ran into a similar issue. As a workaround, you could try to put parentheses around `var()` so as to separate it from the minus sign. Hope this works!

See also https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/119

**Comment by NMFR** [comment]
This plugin does not really touch any css, it delegates it to the css processor that by default is cssnano. So this is either a cssnano issue or your configured processor. I am afraid i cannot help you here. But if you manage to find the source of the problem please comment in this issue to help anyone that is struggling with the same issue.
