### ISSUE TITLE
Running processor in the wrong phase?

### ISSUE THREAD

**Issue by agubler** [NMFR/optimize-css-assets-webpack-plugin#89]
I am currently using this plugin (atm v3.2.0 as still on webpack 3) with cssnano. The css asset has already been processed through postcss as part of the build pipeline so source maps already exist. 

The source-maps should link through to these original maps and looking at the implementation, the maps are picked out of the assets and passed as the `prev` value to cssnano (and postcss eventually).

However in the `OPTIMIZE_CHUNK_ASSETS` phase the maps are not available in the assets so the source-maps are not created correctly. If I change the plugin to use the `OPTIMIZE_ASSETS` the maps are loaded correctly and after processing through cssnano resolve back to the original source css files as expected.

Have I missed something? Or should it be using a different phase? 

Thanks!

**Comment by NMFR** [comment]
The phase as been changed in newer versions, if you can, please upgrade. I think that will solve the issue. 

Closing, please comment if the issue persists.
