### ISSUE TITLE
Purpose of `to` property

### ISSUE THREAD

**Issue by strarsis** [NMFR/optimize-css-assets-webpack-plugin#9]
From https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/4b06a502d2bce6b6eb1999fcbdee45dcbc7d84f6/index.js#L31
```js
[...]
    return this.options.cssProcessor.process(css, Object.assign({ to: assetName }, this.options.cssProcessorOptions)); 
[...]
````

What is the purpose of the `to` property? cssnano [doesn't seem to document](https://github.com/ben-eb/cssnano/blob/master/docs/content/options.md) or use this option.

**Comment by NMFR** [comment]
It's an postcss option that cssnano passes down the chain.
Its used so the source map is correctly generated by cssnano (when source map generation is enabled in the options).

See this for more info / context:
  - https://github.com/NMFR/optimize-css-assets-webpack-plugin/pull/6
  - https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/5

**Comment by strarsis** [comment]
@NMFR: Thanks for your answer. 
So this is not a cssnano option but an option for the plugins that are ran afterwards.

**Comment by NMFR** [comment]
It's part of the cssnano (cssnano uses postcss internally).

This plugin (optimize-css-assets-webpack-plugin) does not really touches any CSS, it delegates that to the css processor (that is cssnano by default).
