### ISSUE TITLE
EINTERGRITY - Invalid response body while trying to fetch ...

### ISSUE THREAD

**Issue by cpurificacao** [NMFR/optimize-css-assets-webpack-plugin#90]
https://imgur.com/kTIWGwp

Hi guys, can you help me? I get this error while try to config my development enviroment with webpack@4,
in fact, the whole environment works perfectly, only an installation of this plugin has this error

**Comment by NMFR** [comment]
Think this was a npm issue that was solved, please comment if the problem persists and i will reopen.
