### ISSUE TITLE
base64 url with double slash was broken by the plugin

### ISSUE THREAD

**Issue by Lynn-cc** [NMFR/optimize-css-assets-webpack-plugin#94]
examples:
`data:img/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAhxJREFUSA3tk71rU1EYxnMTEoJUkowWwdJ2akEHBfGjCiIF6ZylVUKSm2TqZLGI+A/oIu2UXm8C4lAyF4SWji0tdFLo1Eo7VN0SaBEhH7e/Nz0nPTfGOjiaCyfPc5734zlfCQT6X/8E/vUErL81KBaL9y3LSnued5PcITjUOwR3gsFg2bbtjYt6/NGgXC4P1et1l2aPLmpAbD0SidjpdPqgV15PA9d17zQajU8UxHQRK/4G35Q5pveAK8LlI1ZjPMnlcltnyvnvbwaO41xvtVqy7YHztMACq5xnlb9EY3dRdvcGo1kj5wR+t1AofDG0gM+A875E8DNjRCexsrV8Pj9ZqVQitVrtqejxePxjMpmss5hVTB4buXvMb2DyU2tBTRS+BjvNlVYUpPl7iuVO3Gq1uoQx1FtSOW1gPgp5ZWrdBtNmUDgv5asgxQ8F1af5vhY0YjyjuWC3wTszKJz7GBOkcFlQfW2ONq4FjWi+Hj6DRCKxQOK2TlY4x92EuYd5dvMAbYIzfikau3pu5tJ8KxaLLfo0cyKci7tK4TZjUMcoXAmHwzle0Q/RaC5P1GFMyVx9R9Fo9HYqlTrSgqDvFelAqVQa5hmuMR/WGtjAaBdjwBoDQ0ZsnwVMZjKZ9n0Zem8DSeDPdrnZbL6F2l3NOvUYNZk4oVDoRTabPe4EDNJzB0ZcjAYxeoZ2i3FNxQ7BHYw/cB/fldaH//UETgHHO8S44KbfXgAAAABJRU5ErkJggg==`

`data:img/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAPRJREFUSA1jYBgFwz4EGCnx4cyZMzOB+quZmZnjU1JS9mIzi2wLZs2a5fP////NUEO/Ay3xxWYJEzZbCYnNnj3bSUZGZjcjI+MmqFrOv3//LsSmj2QLgIZn//v3b++TJ0+mAi0JQ7KkFZsFzNgEcYlBDZ8ClTf6/PmzJNCSRCB9Mj09fRk2fUTHAZrhcLOYmJicU1NT98EF0BhEBREew3PwGQ6yi6APCBg+Fc3BGFy8FlBqOF4fUMNwnBZQy3CQBVgjGZhDJ4MkkQEwtYAilGCYI+sBsXFZgBI35BoOsoAFROACwFz6H4hzyXE5LjNHxYdhCAAAg1tuIjgPJx8AAAAASUVORK5CYII=`

`data:img/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAYAAAAmlE46AAAAAXNSR0IArs4c6QAAAG9JREFUKBVjnDlzZigDEmBkZEz8//+/J5IQA1BsO1BsPrIYC5CzClkAqACZC2ZDDUIxDEMRsQKMIIVA52Jag8eE9PR0RiY88nilRjXiCZ4REzjA1P8ZTzigSMHUggMHmPqrgAJfUVRg4YDUgNSCpAB1SCA/Q/BJDwAAAABJRU5ErkJggg==`

I found the `H//U` string in the last line of the first example was turn into `H/U` which made the url broken.

**Comment by NMFR** [comment]
This plugin does not really touch any css, it delegates it to the css processor that by default is cssnano. So this is either a cssnano issue or your configured processor. I am afraid i cannot help you here. But if you manage to find the source of the problem please comment in this issue to help anyone that is struggling with the same issue.
