### ISSUE TITLE
npm install unhandled rejection

### ISSUE THREAD

**Issue by shunsmith** [NMFR/optimize-css-assets-webpack-plugin#95]
I am seeing the following error trying to install this package via npm. The installation freezes after the error occurs.

> Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/andy/.npm/_cacache/content-v2/sha512/0b/0c'

node: 11.8.0
npm: 6.5.0

**Comment by NMFR** [comment]
Not related to `optimize-css-assets-webpack-plugin`.
Most likely you installed node as rot and you are running it as non root.
I suggest using [nvm](https://github.com/nvm-sh/nvm) to install node.
