### ISSUE TITLE
sourceMappingURL comment is removed in minification

### ISSUE THREAD

**Issue by iambalaam** [NMFR/optimize-css-assets-webpack-plugin#98]
I'm struggling to minify my css, and keep the sourceMappingURL comment to my `.css.map` file.

On the `minification` branch of this [minimal repo](https://github.com/iambalaam/minimal-webpack/tree/minification) I have added a minimizer
```
new OptimizeCSSAssetsPlugin({
    cssProcessorOptions: {
        map: { inline: false }
    }
})
```
### Before adding this minimizer
I get unminified `.css` and a `.css.map` file but a correct map back to the `.scss` file.  

### After adding this minimizer
I get minified `.css` and a `.css.map` file, but the sourceMappingURL comment has been removed

**Comment by anlambert** [comment]
I encountered the same issue today. You can find the fix here: https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/81#issuecomment-469722663

**Comment by iambalaam** [comment]
This works correctly - thank you!
